#!/bin/bash

if [ "$1" == "-v" ]
then
  shift
  mvn exec:java -Dexec.mainClass=eu.monnetproject.translation.topics.lsa.LSATrain -Dexec.args="$*"
else
  mvn -q exec:java -Dexec.mainClass=eu.monnetproject.translation.topics.lsa.LSATrain -Dexec.args="$*"
fi
