#!/bin/bash

if [ "$1" == "-v" ]
then
  shift
  mvn exec:java -Dexec.mainClass="eu.monnetproject.bliss.ontology.Onto2Text" -Dexec.args="$*"
else
  mvn -q exec:java -Dexec.mainClass="eu.monnetproject.bliss.ontology.Onto2Text" -Dexec.args="$*"
fi

