#!/bin/bash

if [ "$1" == "-v" ]
then
  shift
  mvn exec:java -Dexec.mainClass=eu.monnetproject.bliss.betalm.CompileModel -Dexec.args="$*"
else
  mvn -q exec:java -Dexec.mainClass=eu.monnetproject.bliss.betalm.CompileModel -Dexec.args="$*"
fi
